<?php

return [
    ['country' => 'Canada', 'dial' => '+1', 'label' => '+1 (Canada)'],
    ['country' => 'Afghanistan', 'dial' => '+93', 'label' => '+93 (Afghanistan)'],
    ['country' => 'Albania', 'dial' => '+355', 'label' => '+355 (Albania)'],
    ['country' => 'Algeria', 'dial' => '+213', 'label' => '+213 (Algeria)'],
    ['country' => 'American Samoa', 'dial' => '+1684', 'label' => '+1684 (American Samoa)'],
    ['country' => 'Andorra', 'dial' => '+376', 'label' => '+376 (Andorra)'],
    ['country' => 'Angola', 'dial' => '+244', 'label' => '+244 (Angola)'],
    ['country' => 'Anguilla', 'dial' => '+1264', 'label' => '+1264 (Anguilla)'],
    ['country' => 'Antarctica', 'dial' => '+672', 'label' => '+672 (Antarctica)'],
    ['country' => 'Antigua and Barbuda', 'dial' => '+1268', 'label' => '+1268 (Antigua and Barbuda)'],
    ['country' => 'Argentina', 'dial' => '+54', 'label' => '+54 (Argentina)'],
    ['country' => 'Armenia', 'dial' => '+374', 'label' => '+374 (Armenia)'],
    ['country' => 'Aruba', 'dial' => '+297', 'label' => '+297 (Aruba)'],
    ['country' => 'Australia', 'dial' => '+61', 'label' => '+61 (Australia)'],
    ['country' => 'Austria', 'dial' => '+43', 'label' => '+43 (Austria)'],
    ['country' => 'Azerbaijan', 'dial' => '+994', 'label' => '+994 (Azerbaijan)'],
    ['country' => 'Bahamas', 'dial' => '+1242', 'label' => '+1242 (Bahamas)'],
    ['country' => 'Bahrain', 'dial' => '+973', 'label' => '+973 (Bahrain)'],
    ['country' => 'Bangladesh', 'dial' => '+880', 'label' => '+880 (Bangladesh)'],
    ['country' => 'Barbados', 'dial' => '+1246', 'label' => '+1246 (Barbados)'],
    ['country' => 'Belarus', 'dial' => '+375', 'label' => '+375 (Belarus)'],
    ['country' => 'Belgium', 'dial' => '+32', 'label' => '+32 (Belgium)'],
    ['country' => 'Belize', 'dial' => '+501', 'label' => '+501 (Belize)'],
    ['country' => 'Benin', 'dial' => '+229', 'label' => '+229 (Benin)'],
    ['country' => 'Bermuda', 'dial' => '+1441', 'label' => '+1441 (Bermuda)'],
    ['country' => 'Bhutan', 'dial' => '+975', 'label' => '+975 (Bhutan)'],
    ['country' => 'Bolivia', 'dial' => '+591', 'label' => '+591 (Bolivia)'],
    ['country' => 'Bosnia and Herzegovina', 'dial' => '+387', 'label' => '+387 (Bosnia and Herzegovina)'],
    ['country' => 'Botswana', 'dial' => '+267', 'label' => '+267 (Botswana)'],
    ['country' => 'Brazil', 'dial' => '+55', 'label' => '+55 (Brazil)'],
    ['country' => 'British Indian Ocean Territory', 'dial' => '+246', 'label' => '+246 (British Indian Ocean Territory)'],
    ['country' => 'British Virgin Islands', 'dial' => '+1284', 'label' => '+1284 (British Virgin Islands)'],
    ['country' => 'Brunei', 'dial' => '+673', 'label' => '+673 (Brunei)'],
    ['country' => 'Bulgaria', 'dial' => '+359', 'label' => '+359 (Bulgaria)'],
    ['country' => 'Burkina Faso', 'dial' => '+226', 'label' => '+226 (Burkina Faso)'],
    ['country' => 'Burundi', 'dial' => '+257', 'label' => '+257 (Burundi)'],
    ['country' => 'Cambodia', 'dial' => '+855', 'label' => '+855 (Cambodia)'],
    ['country' => 'Cameroon', 'dial' => '+237', 'label' => '+237 (Cameroon)'],
    ['country' => 'Cape Verde', 'dial' => '+238', 'label' => '+238 (Cape Verde)'],
    ['country' => 'Cayman Islands', 'dial' => '+1345', 'label' => '+1345 (Cayman Islands)'],
    ['country' => 'Central African Republic', 'dial' => '+236', 'label' => '+236 (Central African Republic)'],
    ['country' => 'Chad', 'dial' => '+235', 'label' => '+235 (Chad)'],
    ['country' => 'Chile', 'dial' => '+56', 'label' => '+56 (Chile)'],
    ['country' => 'China', 'dial' => '+86', 'label' => '+86 (China)'],
    ['country' => 'Colombia', 'dial' => '+57', 'label' => '+57 (Colombia)'],
    ['country' => 'Comoros', 'dial' => '+269', 'label' => '+269 (Comoros)'],
    ['country' => 'Congo', 'dial' => '+242', 'label' => '+242 (Congo)'],
    ['country' => 'Cook Islands', 'dial' => '+682', 'label' => '+682 (Cook Islands)'],
    ['country' => 'Costa Rica', 'dial' => '+506', 'label' => '+506 (Costa Rica)'],
    ['country' => 'Croatia', 'dial' => '+385', 'label' => '+385 (Croatia)'],
    ['country' => 'Cuba', 'dial' => '+53', 'label' => '+53 (Cuba)'],
    ['country' => 'Curaçao', 'dial' => '+599', 'label' => '+599 (Curaçao)'],
    ['country' => 'Cyprus', 'dial' => '+357', 'label' => '+357 (Cyprus)'],
    ['country' => 'Czech Republic', 'dial' => '+420', 'label' => '+420 (Czech Republic)'],
    ['country' => 'Côte d’Ivoire', 'dial' => '+225', 'label' => '+225 (Côte d’Ivoire)'],
    ['country' => 'Democratic Republic of the Congo', 'dial' => '+243', 'label' => '+243 (Democratic Republic of the Congo)'],
    ['country' => 'Denmark', 'dial' => '+45', 'label' => '+45 (Denmark)'],
    ['country' => 'Djibouti', 'dial' => '+253', 'label' => '+253 (Djibouti)'],
    ['country' => 'Dominica', 'dial' => '+1767', 'label' => '+1767 (Dominica)'],
    ['country' => 'Dominican Republic', 'dial' => '+1', 'label' => '+1 (Dominican Republic)'],
    ['country' => 'Ecuador', 'dial' => '+593', 'label' => '+593 (Ecuador)'],
    ['country' => 'Egypt', 'dial' => '+20', 'label' => '+20 (Egypt)'],
    ['country' => 'El Salvador', 'dial' => '+503', 'label' => '+503 (El Salvador)'],
    ['country' => 'Equatorial Guinea', 'dial' => '+240', 'label' => '+240 (Equatorial Guinea)'],
    ['country' => 'Eritrea', 'dial' => '+291', 'label' => '+291 (Eritrea)'],
    ['country' => 'Estonia', 'dial' => '+372', 'label' => '+372 (Estonia)'],
    ['country' => 'Eswatini', 'dial' => '+268', 'label' => '+268 (Eswatini)'],
    ['country' => 'Ethiopia', 'dial' => '+251', 'label' => '+251 (Ethiopia)'],
    ['country' => 'Falkland Islands', 'dial' => '+500', 'label' => '+500 (Falkland Islands)'],
    ['country' => 'Faroe Islands', 'dial' => '+298', 'label' => '+298 (Faroe Islands)'],
    ['country' => 'Fiji', 'dial' => '+679', 'label' => '+679 (Fiji)'],
    ['country' => 'Finland', 'dial' => '+358', 'label' => '+358 (Finland)'],
    ['country' => 'France', 'dial' => '+33', 'label' => '+33 (France)'],
    ['country' => 'French Guiana', 'dial' => '+594', 'label' => '+594 (French Guiana)'],
    ['country' => 'French Polynesia', 'dial' => '+689', 'label' => '+689 (French Polynesia)'],
    ['country' => 'French Southern Territories', 'dial' => '+262', 'label' => '+262 (French Southern Territories)'],
    ['country' => 'Gabon', 'dial' => '+241', 'label' => '+241 (Gabon)'],
    ['country' => 'Gambia', 'dial' => '+220', 'label' => '+220 (Gambia)'],
    ['country' => 'Georgia', 'dial' => '+995', 'label' => '+995 (Georgia)'],
    ['country' => 'Germany', 'dial' => '+49', 'label' => '+49 (Germany)'],
    ['country' => 'Ghana', 'dial' => '+233', 'label' => '+233 (Ghana)'],
    ['country' => 'Gibraltar', 'dial' => '+350', 'label' => '+350 (Gibraltar)'],
    ['country' => 'Greece', 'dial' => '+30', 'label' => '+30 (Greece)'],
    ['country' => 'Greenland', 'dial' => '+299', 'label' => '+299 (Greenland)'],
    ['country' => 'Grenada', 'dial' => '+1473', 'label' => '+1473 (Grenada)'],
    ['country' => 'Guadeloupe', 'dial' => '+590', 'label' => '+590 (Guadeloupe)'],
    ['country' => 'Guam', 'dial' => '+1671', 'label' => '+1671 (Guam)'],
    ['country' => 'Guatemala', 'dial' => '+502', 'label' => '+502 (Guatemala)'],
    ['country' => 'Guernsey', 'dial' => '+44', 'label' => '+44 (Guernsey)'],
    ['country' => 'Guinea', 'dial' => '+224', 'label' => '+224 (Guinea)'],
    ['country' => 'Guinea-Bissau', 'dial' => '+245', 'label' => '+245 (Guinea-Bissau)'],
    ['country' => 'Guyana', 'dial' => '+592', 'label' => '+592 (Guyana)'],
    ['country' => 'Haiti', 'dial' => '+509', 'label' => '+509 (Haiti)'],
    ['country' => 'Honduras', 'dial' => '+504', 'label' => '+504 (Honduras)'],
    ['country' => 'Hong Kong', 'dial' => '+852', 'label' => '+852 (Hong Kong)'],
    ['country' => 'Hungary', 'dial' => '+36', 'label' => '+36 (Hungary)'],
    ['country' => 'Iceland', 'dial' => '+354', 'label' => '+354 (Iceland)'],
    ['country' => 'India', 'dial' => '+91', 'label' => '+91 (India)'],
    ['country' => 'Indonesia', 'dial' => '+62', 'label' => '+62 (Indonesia)'],
    ['country' => 'Iran', 'dial' => '+98', 'label' => '+98 (Iran)'],
    ['country' => 'Iraq', 'dial' => '+964', 'label' => '+964 (Iraq)'],
    ['country' => 'Ireland', 'dial' => '+353', 'label' => '+353 (Ireland)'],
    ['country' => 'Isle of Man', 'dial' => '+44', 'label' => '+44 (Isle of Man)'],
    ['country' => 'Israel', 'dial' => '+972', 'label' => '+972 (Israel)'],
    ['country' => 'Italy', 'dial' => '+39', 'label' => '+39 (Italy)'],
    ['country' => 'Jamaica', 'dial' => '+1876', 'label' => '+1876 (Jamaica)'],
    ['country' => 'Japan', 'dial' => '+81', 'label' => '+81 (Japan)'],
    ['country' => 'Jersey', 'dial' => '+44', 'label' => '+44 (Jersey)'],
    ['country' => 'Jordan', 'dial' => '+962', 'label' => '+962 (Jordan)'],
    ['country' => 'Kazakhstan', 'dial' => '+7', 'label' => '+7 (Kazakhstan)'],
    ['country' => 'Kenya', 'dial' => '+254', 'label' => '+254 (Kenya)'],
    ['country' => 'Kiribati', 'dial' => '+686', 'label' => '+686 (Kiribati)'],
    ['country' => 'Kosovo', 'dial' => '+383', 'label' => '+383 (Kosovo)'],
    ['country' => 'Kuwait', 'dial' => '+965', 'label' => '+965 (Kuwait)'],
    ['country' => 'Kyrgyzstan', 'dial' => '+996', 'label' => '+996 (Kyrgyzstan)'],
    ['country' => 'Laos', 'dial' => '+856', 'label' => '+856 (Laos)'],
    ['country' => 'Latvia', 'dial' => '+371', 'label' => '+371 (Latvia)'],
    ['country' => 'Lebanon', 'dial' => '+961', 'label' => '+961 (Lebanon)'],
    ['country' => 'Lesotho', 'dial' => '+266', 'label' => '+266 (Lesotho)'],
    ['country' => 'Liberia', 'dial' => '+231', 'label' => '+231 (Liberia)'],
    ['country' => 'Libya', 'dial' => '+218', 'label' => '+218 (Libya)'],
    ['country' => 'Liechtenstein', 'dial' => '+423', 'label' => '+423 (Liechtenstein)'],
    ['country' => 'Lithuania', 'dial' => '+370', 'label' => '+370 (Lithuania)'],
    ['country' => 'Luxembourg', 'dial' => '+352', 'label' => '+352 (Luxembourg)'],
    ['country' => 'Macau', 'dial' => '+853', 'label' => '+853 (Macau)'],
    ['country' => 'Madagascar', 'dial' => '+261', 'label' => '+261 (Madagascar)'],
    ['country' => 'Malawi', 'dial' => '+265', 'label' => '+265 (Malawi)'],
    ['country' => 'Malaysia', 'dial' => '+60', 'label' => '+60 (Malaysia)'],
    ['country' => 'Maldives', 'dial' => '+960', 'label' => '+960 (Maldives)'],
    ['country' => 'Mali', 'dial' => '+223', 'label' => '+223 (Mali)'],
    ['country' => 'Malta', 'dial' => '+356', 'label' => '+356 (Malta)'],
    ['country' => 'Marshall Islands', 'dial' => '+692', 'label' => '+692 (Marshall Islands)'],
    ['country' => 'Martinique', 'dial' => '+596', 'label' => '+596 (Martinique)'],
    ['country' => 'Mauritania', 'dial' => '+222', 'label' => '+222 (Mauritania)'],
    ['country' => 'Mauritius', 'dial' => '+230', 'label' => '+230 (Mauritius)'],
    ['country' => 'Mayotte', 'dial' => '+262', 'label' => '+262 (Mayotte)'],
    ['country' => 'Mexico', 'dial' => '+52', 'label' => '+52 (Mexico)'],
    ['country' => 'Micronesia', 'dial' => '+691', 'label' => '+691 (Micronesia)'],
    ['country' => 'Moldova', 'dial' => '+373', 'label' => '+373 (Moldova)'],
    ['country' => 'Monaco', 'dial' => '+377', 'label' => '+377 (Monaco)'],
    ['country' => 'Mongolia', 'dial' => '+976', 'label' => '+976 (Mongolia)'],
    ['country' => 'Montenegro', 'dial' => '+382', 'label' => '+382 (Montenegro)'],
    ['country' => 'Montserrat', 'dial' => '+1664', 'label' => '+1664 (Montserrat)'],
    ['country' => 'Morocco', 'dial' => '+212', 'label' => '+212 (Morocco)'],
    ['country' => 'Mozambique', 'dial' => '+258', 'label' => '+258 (Mozambique)'],
    ['country' => 'Myanmar', 'dial' => '+95', 'label' => '+95 (Myanmar)'],
    ['country' => 'Namibia', 'dial' => '+264', 'label' => '+264 (Namibia)'],
    ['country' => 'Nauru', 'dial' => '+674', 'label' => '+674 (Nauru)'],
    ['country' => 'Nepal', 'dial' => '+977', 'label' => '+977 (Nepal)'],
    ['country' => 'Netherlands', 'dial' => '+31', 'label' => '+31 (Netherlands)'],
    ['country' => 'New Caledonia', 'dial' => '+687', 'label' => '+687 (New Caledonia)'],
    ['country' => 'New Zealand', 'dial' => '+64', 'label' => '+64 (New Zealand)'],
    ['country' => 'Nicaragua', 'dial' => '+505', 'label' => '+505 (Nicaragua)'],
    ['country' => 'Niger', 'dial' => '+227', 'label' => '+227 (Niger)'],
    ['country' => 'Nigeria', 'dial' => '+234', 'label' => '+234 (Nigeria)'],
    ['country' => 'Niue', 'dial' => '+683', 'label' => '+683 (Niue)'],
    ['country' => 'North Korea', 'dial' => '+850', 'label' => '+850 (North Korea)'],
    ['country' => 'North Macedonia', 'dial' => '+389', 'label' => '+389 (North Macedonia)'],
    ['country' => 'Northern Mariana Islands', 'dial' => '+1670', 'label' => '+1670 (Northern Mariana Islands)'],
    ['country' => 'Norway', 'dial' => '+47', 'label' => '+47 (Norway)'],
    ['country' => 'Oman', 'dial' => '+968', 'label' => '+968 (Oman)'],
    ['country' => 'Pakistan', 'dial' => '+92', 'label' => '+92 (Pakistan)'],
    ['country' => 'Palau', 'dial' => '+680', 'label' => '+680 (Palau)'],
    ['country' => 'Palestine', 'dial' => '+970', 'label' => '+970 (Palestine)'],
    ['country' => 'Panama', 'dial' => '+507', 'label' => '+507 (Panama)'],
    ['country' => 'Papua New Guinea', 'dial' => '+675', 'label' => '+675 (Papua New Guinea)'],
    ['country' => 'Paraguay', 'dial' => '+595', 'label' => '+595 (Paraguay)'],
    ['country' => 'Peru', 'dial' => '+51', 'label' => '+51 (Peru)'],
    ['country' => 'Philippines', 'dial' => '+63', 'label' => '+63 (Philippines)'],
    ['country' => 'Poland', 'dial' => '+48', 'label' => '+48 (Poland)'],
    ['country' => 'Portugal', 'dial' => '+351', 'label' => '+351 (Portugal)'],
    ['country' => 'Puerto Rico', 'dial' => '+1', 'label' => '+1 (Puerto Rico)'],
    ['country' => 'Qatar', 'dial' => '+974', 'label' => '+974 (Qatar)'],
    ['country' => 'Romania', 'dial' => '+40', 'label' => '+40 (Romania)'],
    ['country' => 'Russia', 'dial' => '+7', 'label' => '+7 (Russia)'],
    ['country' => 'Rwanda', 'dial' => '+250', 'label' => '+250 (Rwanda)'],
    ['country' => 'Réunion', 'dial' => '+262', 'label' => '+262 (Réunion)'],
    ['country' => 'Saint Barthélemy', 'dial' => '+590', 'label' => '+590 (Saint Barthélemy)'],
    ['country' => 'Saint Helena', 'dial' => '+290', 'label' => '+290 (Saint Helena)'],
    ['country' => 'Saint Kitts and Nevis', 'dial' => '+1869', 'label' => '+1869 (Saint Kitts and Nevis)'],
    ['country' => 'Saint Lucia', 'dial' => '+1758', 'label' => '+1758 (Saint Lucia)'],
    ['country' => 'Saint Martin', 'dial' => '+590', 'label' => '+590 (Saint Martin)'],
    ['country' => 'Saint Pierre and Miquelon', 'dial' => '+508', 'label' => '+508 (Saint Pierre and Miquelon)'],
    ['country' => 'Saint Vincent and the Grenadines', 'dial' => '+1784', 'label' => '+1784 (Saint Vincent and the Grenadines)'],
    ['country' => 'Samoa', 'dial' => '+685', 'label' => '+685 (Samoa)'],
    ['country' => 'San Marino', 'dial' => '+378', 'label' => '+378 (San Marino)'],
    ['country' => 'Saudi Arabia', 'dial' => '+966', 'label' => '+966 (Saudi Arabia)'],
    ['country' => 'Senegal', 'dial' => '+221', 'label' => '+221 (Senegal)'],
    ['country' => 'Serbia', 'dial' => '+381', 'label' => '+381 (Serbia)'],
    ['country' => 'Seychelles', 'dial' => '+248', 'label' => '+248 (Seychelles)'],
    ['country' => 'Sierra Leone', 'dial' => '+232', 'label' => '+232 (Sierra Leone)'],
    ['country' => 'Singapore', 'dial' => '+65', 'label' => '+65 (Singapore)'],
    ['country' => 'Sint Maarten', 'dial' => '+1721', 'label' => '+1721 (Sint Maarten)'],
    ['country' => 'Slovakia', 'dial' => '+421', 'label' => '+421 (Slovakia)'],
    ['country' => 'Slovenia', 'dial' => '+386', 'label' => '+386 (Slovenia)'],
    ['country' => 'Solomon Islands', 'dial' => '+677', 'label' => '+677 (Solomon Islands)'],
    ['country' => 'Somalia', 'dial' => '+252', 'label' => '+252 (Somalia)'],
    ['country' => 'South Africa', 'dial' => '+27', 'label' => '+27 (South Africa)'],
    ['country' => 'South Korea', 'dial' => '+82', 'label' => '+82 (South Korea)'],
    ['country' => 'South Sudan', 'dial' => '+211', 'label' => '+211 (South Sudan)'],
    ['country' => 'Spain', 'dial' => '+34', 'label' => '+34 (Spain)'],
    ['country' => 'Sri Lanka', 'dial' => '+94', 'label' => '+94 (Sri Lanka)'],
    ['country' => 'Sudan', 'dial' => '+249', 'label' => '+249 (Sudan)'],
    ['country' => 'Suriname', 'dial' => '+597', 'label' => '+597 (Suriname)'],
    ['country' => 'Svalbard and Jan Mayen', 'dial' => '+47', 'label' => '+47 (Svalbard and Jan Mayen)'],
    ['country' => 'Sweden', 'dial' => '+46', 'label' => '+46 (Sweden)'],
    ['country' => 'Switzerland', 'dial' => '+41', 'label' => '+41 (Switzerland)'],
    ['country' => 'Syria', 'dial' => '+963', 'label' => '+963 (Syria)'],
    ['country' => 'São Tomé and Príncipe', 'dial' => '+239', 'label' => '+239 (São Tomé and Príncipe)'],
    ['country' => 'Taiwan', 'dial' => '+886', 'label' => '+886 (Taiwan)'],
    ['country' => 'Tajikistan', 'dial' => '+992', 'label' => '+992 (Tajikistan)'],
    ['country' => 'Tanzania', 'dial' => '+255', 'label' => '+255 (Tanzania)'],
    ['country' => 'Thailand', 'dial' => '+66', 'label' => '+66 (Thailand)'],
    ['country' => 'Timor-Leste', 'dial' => '+670', 'label' => '+670 (Timor-Leste)'],
    ['country' => 'Togo', 'dial' => '+228', 'label' => '+228 (Togo)'],
    ['country' => 'Tokelau', 'dial' => '+690', 'label' => '+690 (Tokelau)'],
    ['country' => 'Tonga', 'dial' => '+676', 'label' => '+676 (Tonga)'],
    ['country' => 'Trinidad and Tobago', 'dial' => '+1868', 'label' => '+1868 (Trinidad and Tobago)'],
    ['country' => 'Tunisia', 'dial' => '+216', 'label' => '+216 (Tunisia)'],
    ['country' => 'Turkey', 'dial' => '+90', 'label' => '+90 (Turkey)'],
    ['country' => 'Turkmenistan', 'dial' => '+993', 'label' => '+993 (Turkmenistan)'],
    ['country' => 'Turks and Caicos Islands', 'dial' => '+1649', 'label' => '+1649 (Turks and Caicos Islands)'],
    ['country' => 'Tuvalu', 'dial' => '+688', 'label' => '+688 (Tuvalu)'],
    ['country' => 'Uganda', 'dial' => '+256', 'label' => '+256 (Uganda)'],
    ['country' => 'Ukraine', 'dial' => '+380', 'label' => '+380 (Ukraine)'],
    ['country' => 'United Arab Emirates', 'dial' => '+971', 'label' => '+971 (United Arab Emirates)'],
    ['country' => 'United Kingdom', 'dial' => '+44', 'label' => '+44 (United Kingdom)'],
    ['country' => 'United States', 'dial' => '+1', 'label' => '+1 (United States)'],
    ['country' => 'Uruguay', 'dial' => '+598', 'label' => '+598 (Uruguay)'],
    ['country' => 'Uzbekistan', 'dial' => '+998', 'label' => '+998 (Uzbekistan)'],
    ['country' => 'Vanuatu', 'dial' => '+678', 'label' => '+678 (Vanuatu)'],
    ['country' => 'Vatican City', 'dial' => '+379', 'label' => '+379 (Vatican City)'],
    ['country' => 'Venezuela', 'dial' => '+58', 'label' => '+58 (Venezuela)'],
    ['country' => 'Vietnam', 'dial' => '+84', 'label' => '+84 (Vietnam)'],
    ['country' => 'Virgin Islands (British)', 'dial' => '+1284', 'label' => '+1284 (Virgin Islands (British))'],
    ['country' => 'Virgin Islands (U.S.)', 'dial' => '+1340', 'label' => '+1340 (Virgin Islands (U.S.))'],
    ['country' => 'Wallis and Futuna', 'dial' => '+681', 'label' => '+681 (Wallis and Futuna)'],
    ['country' => 'Western Sahara', 'dial' => '+212', 'label' => '+212 (Western Sahara)'],
    ['country' => 'Yemen', 'dial' => '+967', 'label' => '+967 (Yemen)'],
    ['country' => 'Zambia', 'dial' => '+260', 'label' => '+260 (Zambia)'],
    ['country' => 'Zimbabwe', 'dial' => '+263', 'label' => '+263 (Zimbabwe)'],
];